/*
 * Copyright contributors to the Galasa project
 */

package cmd

// Security vulnerability report generated by galasabld ossindex command
type SecVulnYamlReport struct {
	Vulnerabilities []Vulnerability `yaml:"cves"`
}

type Vulnerability struct {
	Cve                string          `yaml:"cve"`
	VulnerableArtifact string          `yaml:"vulnerableArtifact"`
	CvssScore          float64         `yaml:"cvssScore"`
	DirectProjects     []DirectProject `yaml:"directlyAffectedProjects"`
}

type DirectProject struct {
	ProjectName       string             `yaml:"name"`
	DependencyChain   string             `yaml:"dependencyChain"`
	TransientProjects []TransientProject `yaml:"indirectlyAffectedProjects"`
}

type TransientProject struct {
	ProjectName     string `yaml:"name"`
	DependencyChain string `yaml:"dependencyChain"`
}

// Acceptance report written by approvers
type AcceptanceYamlReport struct {
	Cves []AcceptanceCve `yaml:"cves"`
}

type AcceptanceCve struct {
	Cve        string `yaml:"cve"`
	Comment    string `yaml:"comment"`
	ReviewDate string `yaml:"reviewDate"`
}
