/*
 * Copyright contributors to the Galasa project
 */

package cmd

// Security vulnerability report generated by galasabld ossindex command
type YamlReport struct {
	Vulnerabilities []Vulnerability `yaml:"cves"`
}

type Vulnerability struct {
	Cve       string    `yaml:"cve"`
	CvssScore float64   `yaml:"cvssScore"`
	Projects  []Project `yaml:"projects"`
}

type Project struct {
	Project         string `yaml:"name"`
	DependencyType  string `yaml:"dependencyType"`
	DependencyChain string `yaml:"dependencyChain"`
}

// Acceptance report written by approvers
type AcceptanceYamlReport struct {
	Cves []AcceptanceCve `yaml:"cves"`
}

type AcceptanceCve struct {
	Cve        string `yaml:"cve"`
	Comment    string `yaml:"comment"`
	ReviewDate string `yaml:"reviewDate"`
}
