name: PR-build

on:
    pull_request:
        branches: [main]
        paths:
            - '!**.txt'
            - '!**.md'
    workflow_dispatch:

env:
  IMAGE_TAG: latest 

jobs:
    build-galasabld:
        name: build Galasabld 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup up Go
              uses: actions/setup-go@v5
              with: 
                go-version: 1.22
            
            - name: Build galasabld using the makefile
              run: |
                make all 
            
            - name: Build Galasa Image
              run: |
               docker build -t galasabld:$IMAGE_TAG --build-arg=linux-amd64 -f Dockerfile.galasabld ./dockerfiles/galasabld
               docker run --rm galasabld:latest
    


    build-openapi2beans:
        name: build Openapi2beans
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
        
            - name: Setup up Go
              uses: actions/setup-go@v5
              with: 
                go-version: 1.22
                    
            - name: Build openapi2beans using the makefile
              run: |
               cd openapi2beans
               make all 
                    
            - name: Build Galasa Image
              run: |
               docker build -t openapi2beans:$IMAGE_TAG --build-arg=linux-x86_64 -f Dockerfile.openapi2beans ./dockerfiles/openapi2beans
               docker run --rm openapi2beans:$IMAGE_TAG  

            
            

            
            

